import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';
import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

interface TailwindClassInputProps {
   value: string;
   onChange: (value: string) => void;
   placeholder?: string;
   id?: string;
   className?: string;
}

// Generate color classes for all variants
const generateColorClasses = () => {
   const colors = [
      'slate',
      'gray',
      'zinc',
      'neutral',
      'stone',
      'red',
      'orange',
      'amber',
      'yellow',
      'lime',
      'green',
      'emerald',
      'teal',
      'cyan',
      'sky',
      'blue',
      'indigo',
      'violet',
      'purple',
      'fuchsia',
      'pink',
      'rose',
   ];
   const shades = [
      '50',
      '100',
      '200',
      '300',
      '400',
      '500',
      '600',
      '700',
      '800',
      '900',
      '950',
   ];
   const properties = ['text', 'bg', 'border'];

   const classes: string[] = [];
   properties.forEach((prop) => {
      colors.forEach((color) => {
         shades.forEach((shade) => {
            classes.push(`${prop}-${color}-${shade}`);
            classes.push(`hover:${prop}-${color}-${shade}`);
         });
      });
   });

   return classes;
};

// Generate gradient color classes (from-*, via-*, to-*)
const generateGradientColorClasses = () => {
   const colors = [
      'slate',
      'gray',
      'zinc',
      'neutral',
      'stone',
      'red',
      'orange',
      'amber',
      'yellow',
      'lime',
      'green',
      'emerald',
      'teal',
      'cyan',
      'sky',
      'blue',
      'indigo',
      'violet',
      'purple',
      'fuchsia',
      'pink',
      'rose',
   ];
   const shades = [
      '50',
      '100',
      '200',
      '300',
      '400',
      '500',
      '600',
      '700',
      '800',
      '900',
      '950',
   ];
   const properties = ['from', 'via', 'to'];

   const classes: string[] = [];
   properties.forEach((prop) => {
      colors.forEach((color) => {
         shades.forEach((shade) => {
            classes.push(`${prop}-${color}-${shade}`);
         });
      });
   });

   return classes;
};

export const TAILWIND_CLASSES = [
   // Layout
   'flex',
   'inline-flex',
   'grid',
   'inline-grid',
   'block',
   'inline-block',
   'inline',
   'hidden',
   'flex-row',
   'flex-col',
   'flex-wrap',
   'flex-nowrap',
   'flex-row-reverse',
   'flex-col-reverse',
   'items-start',
   'items-center',
   'items-end',
   'items-baseline',
   'items-stretch',
   'justify-start',
   'justify-center',
   'justify-end',
   'justify-between',
   'justify-around',
   'justify-evenly',
   'content-start',
   'content-center',
   'content-end',
   'content-between',
   'content-around',
   'content-evenly',
   'self-auto',
   'self-start',
   'self-center',
   'self-end',
   'self-stretch',
   'gap-0',
   'gap-px',
   'gap-0.5',
   'gap-1',
   'gap-1.5',
   'gap-2',
   'gap-2.5',
   'gap-3',
   'gap-3.5',
   'gap-4',
   'gap-5',
   'gap-6',
   'gap-7',
   'gap-8',
   'gap-9',
   'gap-10',
   'gap-11',
   'gap-12',
   'gap-14',
   'gap-16',
   'gap-20',
   'gap-24',
   'gap-28',
   'gap-32',
   'gap-x-0',
   'gap-x-px',
   'gap-x-0.5',
   'gap-x-1',
   'gap-x-1.5',
   'gap-x-2',
   'gap-x-2.5',
   'gap-x-3',
   'gap-x-3.5',
   'gap-x-4',
   'gap-x-5',
   'gap-x-6',
   'gap-x-8',
   'gap-x-10',
   'gap-x-12',
   'gap-x-16',
   'gap-y-0',
   'gap-y-px',
   'gap-y-0.5',
   'gap-y-1',
   'gap-y-1.5',
   'gap-y-2',
   'gap-y-2.5',
   'gap-y-3',
   'gap-y-3.5',
   'gap-y-4',
   'gap-y-5',
   'gap-y-6',
   'gap-y-8',
   'gap-y-10',
   'gap-y-12',
   'gap-y-16',
   'grid-cols-1',
   'grid-cols-2',
   'grid-cols-3',
   'grid-cols-4',
   'grid-cols-5',
   'grid-cols-6',
   'grid-cols-7',
   'grid-cols-8',
   'grid-cols-9',
   'grid-cols-10',
   'grid-cols-11',
   'grid-cols-12',
   'col-span-1',
   'col-span-2',
   'col-span-3',
   'col-span-4',
   'col-span-5',
   'col-span-6',
   'col-span-7',
   'col-span-8',
   'col-span-9',
   'col-span-10',
   'col-span-11',
   'col-span-12',
   'col-span-full',
   'grid-rows-1',
   'grid-rows-2',
   'grid-rows-3',
   'grid-rows-4',
   'grid-rows-5',
   'grid-rows-6',
   'row-span-1',
   'row-span-2',
   'row-span-3',
   'row-span-4',
   'row-span-5',
   'row-span-6',
   'row-span-full',
   'flex-1',
   'flex-auto',
   'flex-initial',
   'flex-none',
   'grow',
   'grow-0',
   'shrink',
   'shrink-0',
   'order-1',
   'order-2',
   'order-3',
   'order-4',
   'order-5',
   'order-6',
   'order-first',
   'order-last',
   'order-none',

   // Spacing - Padding
   'p-0',
   'p-0.5',
   'p-1',
   'p-1.5',
   'p-2',
   'p-2.5',
   'p-3',
   'p-3.5',
   'p-4',
   'p-5',
   'p-6',
   'p-7',
   'p-8',
   'p-9',
   'p-10',
   'p-11',
   'p-12',
   'p-14',
   'p-16',
   'p-20',
   'p-24',
   'p-28',
   'p-32',
   'p-36',
   'p-40',
   'p-44',
   'p-48',
   'p-52',
   'p-56',
   'p-60',
   'p-64',
   'p-px',
   'px-0',
   'px-0.5',
   'px-1',
   'px-1.5',
   'px-2',
   'px-2.5',
   'px-3',
   'px-3.5',
   'px-4',
   'px-5',
   'px-6',
   'px-7',
   'px-8',
   'px-10',
   'px-12',
   'px-14',
   'px-16',
   'px-20',
   'px-24',
   'px-32',
   'px-px',
   'py-0',
   'py-0.5',
   'py-1',
   'py-1.5',
   'py-2',
   'py-2.5',
   'py-3',
   'py-3.5',
   'py-4',
   'py-5',
   'py-6',
   'py-7',
   'py-8',
   'py-10',
   'py-12',
   'py-14',
   'py-16',
   'py-20',
   'py-24',
   'py-32',
   'py-px',
   'pt-0',
   'pt-0.5',
   'pt-1',
   'pt-1.5',
   'pt-2',
   'pt-2.5',
   'pt-3',
   'pt-3.5',
   'pt-4',
   'pt-5',
   'pt-6',
   'pt-8',
   'pt-10',
   'pt-12',
   'pt-16',
   'pt-20',
   'pt-24',
   'pt-32',
   'pt-px',
   'pr-0',
   'pr-0.5',
   'pr-1',
   'pr-1.5',
   'pr-2',
   'pr-2.5',
   'pr-3',
   'pr-3.5',
   'pr-4',
   'pr-5',
   'pr-6',
   'pr-8',
   'pr-10',
   'pr-12',
   'pr-16',
   'pr-20',
   'pr-24',
   'pr-32',
   'pr-px',
   'pb-0',
   'pb-0.5',
   'pb-1',
   'pb-1.5',
   'pb-2',
   'pb-2.5',
   'pb-3',
   'pb-3.5',
   'pb-4',
   'pb-5',
   'pb-6',
   'pb-8',
   'pb-10',
   'pb-12',
   'pb-16',
   'pb-20',
   'pb-24',
   'pb-32',
   'pb-px',
   'pl-0',
   'pl-0.5',
   'pl-1',
   'pl-1.5',
   'pl-2',
   'pl-2.5',
   'pl-3',
   'pl-3.5',
   'pl-4',
   'pl-5',
   'pl-6',
   'pl-8',
   'pl-10',
   'pl-12',
   'pl-16',
   'pl-20',
   'pl-24',
   'pl-32',
   'pl-px',

   // Spacing - Margin
   'm-0',
   'm-0.5',
   'm-1',
   'm-1.5',
   'm-2',
   'm-2.5',
   'm-3',
   'm-3.5',
   'm-4',
   'm-5',
   'm-6',
   'm-7',
   'm-8',
   'm-10',
   'm-12',
   'm-16',
   'm-20',
   'm-24',
   'm-32',
   'm-auto',
   'm-px',
   '-m-1',
   '-m-2',
   '-m-3',
   '-m-4',
   '-m-5',
   '-m-6',
   '-m-8',
   '-m-10',
   '-m-12',
   '-m-16',
   'mx-0',
   'mx-0.5',
   'mx-1',
   'mx-1.5',
   'mx-2',
   'mx-2.5',
   'mx-3',
   'mx-3.5',
   'mx-4',
   'mx-5',
   'mx-6',
   'mx-8',
   'mx-10',
   'mx-12',
   'mx-16',
   'mx-20',
   'mx-24',
   'mx-32',
   'mx-auto',
   'mx-px',
   '-mx-1',
   '-mx-2',
   '-mx-3',
   '-mx-4',
   '-mx-5',
   '-mx-6',
   '-mx-8',
   '-mx-10',
   '-mx-12',
   'my-0',
   'my-0.5',
   'my-1',
   'my-1.5',
   'my-2',
   'my-2.5',
   'my-3',
   'my-3.5',
   'my-4',
   'my-5',
   'my-6',
   'my-8',
   'my-10',
   'my-12',
   'my-16',
   'my-20',
   'my-24',
   'my-32',
   'my-auto',
   'my-px',
   '-my-1',
   '-my-2',
   '-my-3',
   '-my-4',
   '-my-5',
   '-my-6',
   '-my-8',
   '-my-10',
   '-my-12',
   'mt-0',
   'mt-0.5',
   'mt-1',
   'mt-1.5',
   'mt-2',
   'mt-2.5',
   'mt-3',
   'mt-3.5',
   'mt-4',
   'mt-5',
   'mt-6',
   'mt-8',
   'mt-10',
   'mt-12',
   'mt-16',
   'mt-20',
   'mt-24',
   'mt-32',
   'mt-auto',
   'mt-px',
   '-mt-1',
   '-mt-2',
   '-mt-3',
   '-mt-4',
   '-mt-5',
   '-mt-6',
   '-mt-8',
   '-mt-10',
   '-mt-12',
   '-mt-16',
   'mr-0',
   'mr-0.5',
   'mr-1',
   'mr-1.5',
   'mr-2',
   'mr-2.5',
   'mr-3',
   'mr-3.5',
   'mr-4',
   'mr-5',
   'mr-6',
   'mr-8',
   'mr-10',
   'mr-12',
   'mr-16',
   'mr-20',
   'mr-24',
   'mr-32',
   'mr-auto',
   'mr-px',
   '-mr-1',
   '-mr-2',
   '-mr-3',
   '-mr-4',
   '-mr-5',
   '-mr-6',
   '-mr-8',
   '-mr-10',
   '-mr-12',
   'mb-0',
   'mb-0.5',
   'mb-1',
   'mb-1.5',
   'mb-2',
   'mb-2.5',
   'mb-3',
   'mb-3.5',
   'mb-4',
   'mb-5',
   'mb-6',
   'mb-8',
   'mb-10',
   'mb-12',
   'mb-16',
   'mb-20',
   'mb-24',
   'mb-32',
   'mb-auto',
   'mb-px',
   '-mb-1',
   '-mb-2',
   '-mb-3',
   '-mb-4',
   '-mb-5',
   '-mb-6',
   '-mb-8',
   '-mb-10',
   '-mb-12',
   '-mb-16',
   'ml-0',
   'ml-0.5',
   'ml-1',
   'ml-1.5',
   'ml-2',
   'ml-2.5',
   'ml-3',
   'ml-3.5',
   'ml-4',
   'ml-5',
   'ml-6',
   'ml-8',
   'ml-10',
   'ml-12',
   'ml-16',
   'ml-20',
   'ml-24',
   'ml-32',
   'ml-auto',
   'ml-px',
   '-ml-1',
   '-ml-2',
   '-ml-3',
   '-ml-4',
   '-ml-5',
   '-ml-6',
   '-ml-8',
   '-ml-10',
   '-ml-12',

   // Space Between
   'space-x-0',
   'space-x-1',
   'space-x-2',
   'space-x-3',
   'space-x-4',
   'space-x-5',
   'space-x-6',
   'space-x-8',
   'space-x-10',
   'space-x-12',
   'space-x-16',
   'space-y-0',
   'space-y-1',
   'space-y-2',
   'space-y-3',
   'space-y-4',
   'space-y-5',
   'space-y-6',
   'space-y-8',
   'space-y-10',
   'space-y-12',
   'space-y-16',
   'space-x-reverse',
   'space-y-reverse',

   // Sizing
   'w-0',
   'w-0.5',
   'w-1',
   'w-1.5',
   'w-2',
   'w-2.5',
   'w-3',
   'w-3.5',
   'w-4',
   'w-5',
   'w-6',
   'w-7',
   'w-8',
   'w-9',
   'w-10',
   'w-11',
   'w-12',
   'w-14',
   'w-16',
   'w-20',
   'w-24',
   'w-28',
   'w-32',
   'w-36',
   'w-40',
   'w-44',
   'w-48',
   'w-52',
   'w-56',
   'w-60',
   'w-64',
   'w-72',
   'w-80',
   'w-96',
   'w-auto',
   'w-full',
   'w-screen',
   'w-min',
   'w-max',
   'w-fit',
   'w-px',
   'w-1/2',
   'w-1/3',
   'w-2/3',
   'w-1/4',
   'w-2/4',
   'w-3/4',
   'w-1/5',
   'w-2/5',
   'w-3/5',
   'w-4/5',
   'w-1/6',
   'w-2/6',
   'w-3/6',
   'w-4/6',
   'w-5/6',
   'w-1/12',
   'w-2/12',
   'w-3/12',
   'w-4/12',
   'w-5/12',
   'w-6/12',
   'w-7/12',
   'w-8/12',
   'w-9/12',
   'w-10/12',
   'w-11/12',
   'h-0',
   'h-0.5',
   'h-1',
   'h-1.5',
   'h-2',
   'h-2.5',
   'h-3',
   'h-3.5',
   'h-4',
   'h-5',
   'h-6',
   'h-7',
   'h-8',
   'h-9',
   'h-10',
   'h-11',
   'h-12',
   'h-14',
   'h-16',
   'h-20',
   'h-24',
   'h-28',
   'h-32',
   'h-36',
   'h-40',
   'h-44',
   'h-48',
   'h-52',
   'h-56',
   'h-60',
   'h-64',
   'h-72',
   'h-80',
   'h-96',
   'h-auto',
   'h-full',
   'h-screen',
   'h-min',
   'h-max',
   'h-fit',
   'h-px',
   'h-1/2',
   'h-1/3',
   'h-2/3',
   'h-1/4',
   'h-2/4',
   'h-3/4',
   'h-1/5',
   'h-2/5',
   'h-3/5',
   'h-4/5',
   'h-1/6',
   'h-2/6',
   'h-3/6',
   'h-4/6',
   'h-5/6',

   // Aspect Ratio
   'aspect-auto',
   'aspect-square',
   'aspect-video',
   'min-w-0',
   'min-w-full',
   'min-w-min',
   'min-w-max',
   'min-w-fit',
   'min-h-0',
   'min-h-full',
   'min-h-screen',
   'min-h-min',
   'min-h-max',
   'min-h-fit',
   'max-w-xs',
   'max-w-sm',
   'max-w-md',
   'max-w-lg',
   'max-w-xl',
   'max-w-2xl',
   'max-w-3xl',
   'max-w-4xl',
   'max-w-5xl',
   'max-w-6xl',
   'max-w-7xl',
   'max-w-full',
   'max-w-min',
   'max-w-max',
   'max-w-fit',
   'max-w-prose',
   'max-w-screen-sm',
   'max-w-screen-md',
   'max-w-screen-lg',
   'max-w-screen-xl',
   'max-h-full',
   'max-h-screen',
   'max-h-min',
   'max-h-max',
   'max-h-fit',
   'max-h-0',
   'max-h-1',
   'max-h-2',
   'max-h-3',
   'max-h-4',
   'max-h-6',
   'max-h-8',
   'max-h-10',
   'max-h-12',
   'max-h-16',
   'max-h-20',
   'max-h-24',
   'max-h-32',
   'max-h-40',
   'max-h-48',
   'max-h-56',
   'max-h-64',
   'max-h-96',

   // Typography
   'text-xs',
   'text-sm',
   'text-base',
   'text-lg',
   'text-xl',
   'text-2xl',
   'text-3xl',
   'text-4xl',
   'text-5xl',
   'text-6xl',
   'text-7xl',
   'text-8xl',
   'text-9xl',
   'font-thin',
   'font-extralight',
   'font-light',
   'font-normal',
   'font-medium',
   'font-semibold',
   'font-bold',
   'font-extrabold',
   'font-black',
   'text-left',
   'text-center',
   'text-right',
   'text-justify',
   'text-start',
   'text-end',
   'text-black',
   'text-white',
   'text-transparent',
   'text-current',
   'uppercase',
   'lowercase',
   'capitalize',
   'normal-case',
   'italic',
   'not-italic',
   'underline',
   'line-through',
   'no-underline',
   'underline-offset-auto',
   'underline-offset-0',
   'underline-offset-1',
   'underline-offset-2',
   'underline-offset-4',
   'underline-offset-8',
   'leading-none',
   'leading-tight',
   'leading-snug',
   'leading-normal',
   'leading-relaxed',
   'leading-loose',
   'leading-3',
   'leading-4',
   'leading-5',
   'leading-6',
   'leading-7',
   'leading-8',
   'leading-9',
   'leading-10',
   'tracking-tighter',
   'tracking-tight',
   'tracking-normal',
   'tracking-wide',
   'tracking-wider',
   'tracking-widest',
   'whitespace-normal',
   'whitespace-nowrap',
   'whitespace-pre',
   'whitespace-pre-line',
   'whitespace-pre-wrap',
   'whitespace-break-spaces',
   'break-normal',
   'break-words',
   'break-all',
   'break-keep',
   'truncate',
   'text-ellipsis',
   'text-clip',
   'align-baseline',
   'align-top',
   'align-middle',
   'align-bottom',
   'align-text-top',
   'align-text-bottom',
   'align-sub',
   'align-super',

   // Borders
   'border',
   'border-0',
   'border-2',
   'border-4',
   'border-8',
   'border-x',
   'border-y',
   'border-t',
   'border-r',
   'border-b',
   'border-l',
   'border-solid',
   'border-dashed',
   'border-dotted',
   'border-double',
   'border-none',
   'border-black',
   'border-white',
   'border-transparent',
   'border-current',
   'rounded',
   'rounded-none',
   'rounded-sm',
   'rounded-md',
   'rounded-lg',
   'rounded-xl',
   'rounded-2xl',
   'rounded-3xl',
   'rounded-full',
   'rounded-t',
   'rounded-r',
   'rounded-b',
   'rounded-l',
   'rounded-tl',
   'rounded-tr',
   'rounded-br',
   'rounded-bl',
   'rounded-tl-none',
   'rounded-tl-sm',
   'rounded-tl-md',
   'rounded-tl-lg',
   'rounded-tl-xl',
   'rounded-tl-2xl',
   'rounded-tl-3xl',
   'rounded-tl-full',
   'rounded-tr-none',
   'rounded-tr-sm',
   'rounded-tr-md',
   'rounded-tr-lg',
   'rounded-tr-xl',
   'rounded-tr-2xl',
   'rounded-tr-3xl',
   'rounded-tr-full',
   'rounded-br-none',
   'rounded-br-sm',
   'rounded-br-md',
   'rounded-br-lg',
   'rounded-br-xl',
   'rounded-br-2xl',
   'rounded-br-3xl',
   'rounded-br-full',
   'rounded-bl-none',
   'rounded-bl-sm',
   'rounded-bl-md',
   'rounded-bl-lg',
   'rounded-bl-xl',
   'rounded-bl-2xl',
   'rounded-bl-3xl',
   'rounded-bl-full',

   // Divide
   'divide-x',
   'divide-x-0',
   'divide-x-2',
   'divide-x-4',
   'divide-x-8',
   'divide-y',
   'divide-y-0',
   'divide-y-2',
   'divide-y-4',
   'divide-y-8',
   'divide-solid',
   'divide-dashed',
   'divide-dotted',
   'divide-double',
   'divide-none',

   // Ring
   'ring',
   'ring-0',
   'ring-1',
   'ring-2',
   'ring-4',
   'ring-8',
   'ring-inset',
   'ring-offset-0',
   'ring-offset-1',
   'ring-offset-2',
   'ring-offset-4',
   'ring-offset-8',

   // Effects
   'shadow',
   'shadow-sm',
   'shadow-md',
   'shadow-lg',
   'shadow-xl',
   'shadow-2xl',
   'shadow-inner',
   'shadow-none',
   'opacity-0',
   'opacity-5',
   'opacity-10',
   'opacity-20',
   'opacity-25',
   'opacity-30',
   'opacity-40',
   'opacity-50',
   'opacity-60',
   'opacity-70',
   'opacity-75',
   'opacity-80',
   'opacity-90',
   'opacity-95',
   'opacity-100',
   'blur',
   'blur-none',
   'blur-sm',
   'blur-md',
   'blur-lg',
   'blur-xl',
   'blur-2xl',
   'blur-3xl',
   'brightness-0',
   'brightness-50',
   'brightness-75',
   'brightness-90',
   'brightness-95',
   'brightness-100',
   'brightness-105',
   'brightness-110',
   'brightness-125',
   'brightness-150',
   'brightness-200',
   'contrast-0',
   'contrast-50',
   'contrast-75',
   'contrast-100',
   'contrast-125',
   'contrast-150',
   'contrast-200',
   'grayscale',
   'grayscale-0',
   'sepia',
   'sepia-0',
   'backdrop-blur',
   'backdrop-blur-none',
   'backdrop-blur-sm',
   'backdrop-blur-md',
   'backdrop-blur-lg',
   'backdrop-blur-xl',
   'backdrop-brightness-0',
   'backdrop-brightness-50',
   'backdrop-brightness-75',
   'backdrop-brightness-90',
   'backdrop-brightness-95',
   'backdrop-brightness-100',
   'backdrop-brightness-105',
   'backdrop-brightness-110',
   'backdrop-brightness-125',
   'backdrop-brightness-150',

   // Positioning
   'static',
   'fixed',
   'absolute',
   'relative',
   'sticky',
   'top-0',
   'top-1',
   'top-2',
   'top-4',
   'top-8',
   'top-auto',
   'right-0',
   'right-1',
   'right-2',
   'right-4',
   'right-8',
   'right-auto',
   'bottom-0',
   'bottom-1',
   'bottom-2',
   'bottom-4',
   'bottom-8',
   'bottom-auto',
   'left-0',
   'left-1',
   'left-2',
   'left-4',
   'left-8',
   'left-auto',
   'inset-0',
   'inset-x-0',
   'inset-y-0',
   'z-0',
   'z-10',
   'z-20',
   'z-30',
   'z-40',
   'z-50',
   'z-auto',
   '-z-10',
   '-z-20',
   '-z-30',
   '-z-40',
   '-z-50',

   // Display & Visibility
   'visible',
   'invisible',
   'overflow-auto',
   'overflow-hidden',
   'overflow-visible',
   'overflow-scroll',
   'overflow-x-auto',
   'overflow-x-hidden',
   'overflow-x-visible',
   'overflow-x-scroll',
   'overflow-y-auto',
   'overflow-y-hidden',
   'overflow-y-visible',
   'overflow-y-scroll',
   'scrollbar-hide',
   'overscroll-auto',
   'overscroll-contain',
   'overscroll-none',
   'overscroll-x-auto',
   'overscroll-x-contain',
   'overscroll-x-none',
   'overscroll-y-auto',
   'overscroll-y-contain',
   'overscroll-y-none',

   // Interactivity
   'cursor-auto',
   'cursor-default',
   'cursor-pointer',
   'cursor-wait',
   'cursor-text',
   'cursor-move',
   'cursor-not-allowed',
   'pointer-events-none',
   'pointer-events-auto',
   'select-none',
   'select-text',
   'select-all',
   'select-auto',

   // Transitions
   'transition',
   'transition-none',
   'transition-all',
   'transition-colors',
   'transition-opacity',
   'transition-shadow',
   'transition-transform',
   'duration-75',
   'duration-100',
   'duration-150',
   'duration-200',
   'duration-300',
   'duration-500',
   'duration-700',
   'duration-1000',
   'ease-linear',
   'ease-in',
   'ease-out',
   'ease-in-out',

   // Transforms
   'scale-0',
   'scale-50',
   'scale-75',
   'scale-90',
   'scale-95',
   'scale-100',
   'scale-105',
   'scale-110',
   'scale-125',
   'scale-150',
   'rotate-0',
   'rotate-45',
   'rotate-90',
   'rotate-180',
   '-rotate-45',
   '-rotate-90',
   '-rotate-180',
   'translate-x-0',
   'translate-x-1',
   'translate-x-2',
   'translate-x-4',
   'translate-x-8',
   'translate-y-0',
   'translate-y-1',
   'translate-y-2',
   'translate-y-4',
   'translate-y-8',
   '-translate-x-1',
   '-translate-x-2',
   '-translate-x-4',
   '-translate-x-8',
   '-translate-x-full',
   '-translate-y-1',
   '-translate-y-2',
   '-translate-y-4',
   '-translate-y-8',
   '-translate-y-full',
   'skew-x-0',
   'skew-x-1',
   'skew-x-2',
   'skew-x-3',
   'skew-x-6',
   'skew-x-12',
   'skew-y-0',
   'skew-y-1',
   'skew-y-2',
   'skew-y-3',
   'skew-y-6',
   'skew-y-12',
   '-skew-x-1',
   '-skew-x-2',
   '-skew-x-3',
   '-skew-x-6',
   '-skew-x-12',
   '-skew-y-1',
   '-skew-y-2',
   '-skew-y-3',
   '-skew-y-6',
   '-skew-y-12',

   // Backgrounds
   'bg-transparent',
   'bg-black',
   'bg-white',
   'bg-current',
   'bg-gradient-to-t',
   'bg-gradient-to-tr',
   'bg-gradient-to-r',
   'bg-gradient-to-br',
   'bg-gradient-to-b',
   'bg-gradient-to-bl',
   'bg-gradient-to-l',
   'bg-gradient-to-tl',
   'from-transparent',
   'from-current',
   'from-black',
   'from-white',
   'via-transparent',
   'via-current',
   'via-black',
   'via-white',
   'to-transparent',
   'to-current',
   'to-black',
   'to-white',
   // Gradient colors - from, via, to with all color shades
   ...generateGradientColorClasses(),
   'bg-cover',
   'bg-contain',
   'bg-auto',
   'bg-center',
   'bg-top',
   'bg-right',
   'bg-bottom',
   'bg-left',
   'bg-repeat',
   'bg-no-repeat',
   'bg-repeat-x',
   'bg-repeat-y',
   'bg-repeat-round',
   'bg-repeat-space',
   'bg-fixed',
   'bg-local',
   'bg-scroll',

   // Object Fit & Position
   'object-contain',
   'object-cover',
   'object-fill',
   'object-none',
   'object-scale-down',
   'object-center',
   'object-top',
   'object-right',
   'object-bottom',
   'object-left',
   'object-right-top',
   'object-right-bottom',
   'object-left-top',
   'object-left-bottom',

   // Common hover states
   'hover:scale-105',
   'hover:scale-110',
   'hover:scale-95',
   'hover:opacity-80',
   'hover:opacity-90',
   'hover:opacity-100',
   'hover:shadow-lg',
   'hover:shadow-xl',
   'hover:shadow-2xl',
   'hover:underline',
   'hover:no-underline',
   'hover:rotate-6',
   'hover:-rotate-6',
   'hover:translate-y-1',
   'hover:-translate-y-1',

   // Focus states
   'focus:outline-none',
   'focus:ring',
   'focus:ring-1',
   'focus:ring-2',
   'focus:ring-4',
   'focus:ring-offset-0',
   'focus:ring-offset-1',
   'focus:ring-offset-2',
   'focus:border-transparent',

   // Active states
   'active:scale-95',
   'active:scale-100',

   // Disabled states
   'disabled:opacity-50',
   'disabled:cursor-not-allowed',

   // Group hover
   'group-hover:scale-105',
   'group-hover:opacity-100',
   'group-hover:translate-x-1',
   'group-hover:translate-y-1',

   // Add all generated color classes
   ...generateColorClasses(),
];

export function TailwindClassInput({
   value,
   onChange,
   placeholder = 'e.g. flex gap-4 rounded-lg shadow-md',
   id,
   className,
}: TailwindClassInputProps) {
   const [suggestions, setSuggestions] = useState<string[]>([]);
   const [showSuggestions, setShowSuggestions] = useState(false);
   const [selectedIndex, setSelectedIndex] = useState(0);
   const [cursorPosition, setCursorPosition] = useState(0);
   const [suggestionsPosition, setSuggestionsPosition] = useState({
      top: 0,
      left: 0,
      width: 0,
   });
   const textareaRef = useRef<HTMLTextAreaElement>(null);
   const suggestionsRef = useRef<HTMLDivElement>(null);

   useEffect(() => {
      const beforeCursor = value.substring(0, cursorPosition);
      const words = beforeCursor.split(/\s+/);
      const currentWord = words[words.length - 1] || '';

      if (currentWord.length > 0) {
         // Check if the current word contains a Tailwind modifier (e.g., md:, hover:, focus:)
         const modifierMatch = currentWord.match(
            /^(xs:|sm:|md:|lg:|xl:|2xl:|hover:|focus:|active:|disabled:|group-hover:|focus-within:|focus-visible:|dark:|first:|last:|odd:|even:|visited:|checked:|required:|invalid:|placeholder:|before:|after:)(.*)$/,
         );

         let filtered: string[];

         if (modifierMatch) {
            // If there's a modifier, filter based on the part after the modifier
            const modifier = modifierMatch[1];
            const searchTerm = modifierMatch[2];

            if (searchTerm.length > 0) {
               // Filter classes and prepend the modifier
               filtered = TAILWIND_CLASSES.filter((cls) =>
                  cls.toLowerCase().startsWith(searchTerm.toLowerCase()),
               )
                  .map((cls) => `${modifier}${cls}`)
                  .slice(0, 15);
            } else {
               // Just typed the modifier, show common classes with that modifier
               filtered = TAILWIND_CLASSES.slice(0, 15).map(
                  (cls) => `${modifier}${cls}`,
               );
            }
         } else {
            // No modifier, filter normally
            filtered = TAILWIND_CLASSES.filter((cls) =>
               cls.toLowerCase().startsWith(currentWord.toLowerCase()),
            ).slice(0, 15);
         }

         // This is derived state from props, not a side effect
         // eslint-disable-next-line
         setSuggestions(filtered);
         setShowSuggestions(filtered.length > 0);
         setSelectedIndex(0);
      } else {
         setShowSuggestions(false);
         setSuggestions([]);
      }
   }, [value, cursorPosition]);

   const insertSuggestion = (suggestion: string) => {
      const beforeCursor = value.substring(0, cursorPosition);
      const afterCursor = value.substring(cursorPosition);
      const words = beforeCursor.split(/\s+/);
      words[words.length - 1] = suggestion;
      const newValue = words.join(' ') + afterCursor;

      onChange(newValue);
      setShowSuggestions(false);

      setTimeout(() => {
         if (textareaRef.current) {
            const newPosition = words.join(' ').length;
            textareaRef.current.setSelectionRange(newPosition, newPosition);
            textareaRef.current.focus();
         }
      }, 0);
   };

   const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
      if (!showSuggestions) {
         return;
      }

      if (e.key === 'ArrowDown') {
         e.preventDefault();
         setSelectedIndex((prev) => (prev + 1) % suggestions.length);
      } else if (e.key === 'ArrowUp') {
         e.preventDefault();
         setSelectedIndex(
            (prev) => (prev - 1 + suggestions.length) % suggestions.length,
         );
      } else if (e.key === 'Enter' || e.key === 'Tab') {
         if (suggestions.length > 0) {
            e.preventDefault();
            insertSuggestion(suggestions[selectedIndex]);
         }
      } else if (e.key === 'Escape') {
         setShowSuggestions(false);
      }
   };

   const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      onChange(e.target.value);
      setCursorPosition(e.target.selectionStart);
   };

   const handleClick = (e: React.MouseEvent<HTMLTextAreaElement>) => {
      setCursorPosition(e.currentTarget.selectionStart);
      updateSuggestionsPosition();
   };

   const updateSuggestionsPosition = () => {
      if (textareaRef.current) {
         const rect = textareaRef.current.getBoundingClientRect();
         setSuggestionsPosition({
            top: rect.bottom + window.scrollY,
            left: rect.left + window.scrollX,
            width: rect.width,
         });
      }
   };

   useEffect(() => {
      if (showSuggestions) {
         updateSuggestionsPosition();
      }
   }, [showSuggestions]);

   useEffect(() => {
      const handleScroll = () => {
         if (showSuggestions) {
            updateSuggestionsPosition();
         }
      };

      window.addEventListener('scroll', handleScroll, true);
      window.addEventListener('resize', handleScroll);

      return () => {
         window.removeEventListener('scroll', handleScroll, true);
         window.removeEventListener('resize', handleScroll);
      };
   }, [showSuggestions]);

   const renderSuggestions = () => {
      if (!showSuggestions || suggestions.length === 0) {
         return null;
      }

      return createPortal(
         <div
            ref={suggestionsRef}
            style={{
               position: 'fixed',
               top: `${suggestionsPosition.top}px`,
               left: `${suggestionsPosition.left}px`,
               width: `${suggestionsPosition.width}px`,
            }}
            className="z-[9999] mt-1 max-h-60 overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md"
         >
            {suggestions.map((suggestion, index) => (
               <div
                  key={suggestion}
                  className={cn(
                     'relative flex cursor-pointer items-center rounded-sm px-2 py-1.5 font-mono text-sm outline-none select-none',
                     index === selectedIndex
                        ? 'bg-accent text-accent-foreground'
                        : 'hover:bg-accent hover:text-accent-foreground',
                  )}
                  onClick={() => insertSuggestion(suggestion)}
                  onMouseEnter={() => setSelectedIndex(index)}
               >
                  {suggestion}
               </div>
            ))}
         </div>,
         document.body,
      );
   };

   return (
      <div className="relative">
         <Textarea
            ref={textareaRef}
            id={id}
            value={value}
            rows={3}
            onChange={handleChange}
            onClick={handleClick}
            onKeyDown={handleKeyDown}
            onKeyUp={(e) => setCursorPosition(e.currentTarget.selectionStart)}
            placeholder={placeholder}
         />

         {renderSuggestions()}
      </div>
   );
}
